[tool.ruff]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "C",   # flake8-comprehensions
    "B",   # flake8-bugbear
    "A",   # flake8-builtins
    "DTZ", # flake8-datetimez
    "T20", # flake8-print
    "SIM", # flake8-simplify
    "PD",  # pandas-vet
]
ignore = [
    "E501",  # line too long, handled by black
    "B008",  # do not perform function calls in argument defaults
    "C901",  # too complex
]

[tool.isort]
known_first_party = ["tools", "motor_controller", "utils", "network_controller"]

[tool.black]
line-length = 100
target-version = ['py310', 'py311']

[tool.coverage.run]
parallel = true
source = ["motor_controller", "network_controller"]
context = '${CONTEXT}'
omit = []

[tool.mypy]
strict = true
ignore_missing_imports = true
exclude = ["tests"]

[tool.pytest.ini_options]
addopts = [
  "--strict-config",
  "--strict-markers",
]
xfail_strict = true
junit_family = "xunit2"
filterwarnings = [
]
